# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        ToBeDoneBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
            entity:
                class: ToBeDoneBundle:User
                property: username

    firewalls:
        default:
            pattern: ^/
            http_basic: ~
            provider: our_db_provider